module Datadog
  module CI
    module TestImpactAnalysis
      class Skippable
        @api: Datadog::CI::Transport::Api::Base?
        @dd_env: String?
        @config_tags: Hash[String, String]

        class Response
          @http_response: Datadog::CI::Transport::Adapters::Net::Response?
          @json: Hash[String, untyped]?

          def self.from_http_response: (Datadog::CI::Transport::Adapters::Net::Response? http_response) -> Response

          def self.from_json: (Hash[String, untyped] json) -> Response

          def ok?: () -> bool

          def correlation_id: () -> String?

          def tests: () -> Set[String]

          def error_message: () -> String?

          private

          def initialize: (Datadog::CI::Transport::Adapters::Net::Response? http_response, Hash[String, untyped]? json) -> void

          def payload: () -> Hash[String, untyped]
        end

        def initialize: (?api: Datadog::CI::Transport::Api::Base?, dd_env: String?, ?config_tags: Hash[String, String]) -> void

        def fetch_skippable_tests: (Datadog::CI::TestSession test_session) -> Response

        private

        def payload: (Datadog::CI::TestSession test_session) -> String
      end
    end
  end
end
