module Datadog
  module CI
    def self.trace_test: (String span_name, ?service_name: String?, ?operation_name: String, ?tags: Hash[untyped, untyped]) ?{ (Datadog::CI::Test test) -> untyped } -> untyped

    def self.start_test: (String span_name, ?service_name: String?, ?operation_name: String, ?tags: Hash[untyped, untyped]) -> Datadog::CI::Test

    def self.trace: (String span_type, String span_name, ?tags: Hash[untyped, untyped]) ?{ (Datadog::CI::Span span) -> untyped } -> untyped

    def self.active_test: () -> Datadog::CI::Test?

    def self.active_span: (String span_type) -> Datadog::CI::Span?

    def self.deactivate_test: (Datadog::CI::Test test) -> void

    def self.components: () -> Datadog::CI::Configuration::Components

    def self.recorder: () -> Datadog::CI::Recorder
  end
end
