module Datadog
  def self.configure: () ?{ (untyped config) -> untyped } -> untyped

  module CI
    class ReservedTypeError < StandardError
    end

    def self.trace_test: (String test_name, String test_suite_name, ?service: String?, ?tags: Hash[untyped, untyped]) ?{ (Datadog::CI::Test? test) -> untyped } -> untyped

    def self.start_test: (String test_name, String test_suite_name, ?service: String?, ?tags: Hash[untyped, untyped]) -> Datadog::CI::Test?

    def self.start_test_session: (?service: String, ?tags: Hash[untyped, untyped], ?total_tests_count: Integer) -> Datadog::CI::TestSession?

    def self.start_test_module: (String test_module_name, ?service: String?, ?tags: Hash[untyped, untyped]) -> Datadog::CI::TestModule?

    def self.start_test_suite: (String test_suite_name, ?service: String?, ?tags: Hash[untyped, untyped]) -> Datadog::CI::TestSuite?

    def self.trace: (String span_name, ?type: String, ?tags: Hash[untyped, untyped]) ?{ (Datadog::CI::Span span) -> untyped } -> untyped

    def self.active_test_session: () -> Datadog::CI::TestSession?

    def self.active_test_module: () -> Datadog::CI::TestModule?

    def self.active_test: () -> Datadog::CI::Test?

    def self.active_test_suite: (?String? test_suite_name) -> Datadog::CI::TestSuite?

    def self.active_span: () -> Datadog::CI::Span?

    private

    def self.components: () -> Datadog::CI::Configuration::Components

    def self.test_visibility: () -> (Datadog::CI::TestVisibility::Component | Datadog::CI::TestVisibility::NullComponent)

    def self.test_optimisation: () -> Datadog::CI::TestOptimisation::Component?

    def self.test_retries: () -> Datadog::CI::TestRetries::Component?

    def self.test_management: () -> (Datadog::CI::TestManagement::Component | Datadog::CI::TestManagement::NullComponent)
  end
end
