module Datadog
  module CI
    module Contrib
      module ActiveSupport
        module Patcher
          include Datadog::CI::Contrib::Patcher

          def self.patch: () -> bool
          def datadog_logs_component: () -> Datadog::CI::Logs::Component
        end
      end
    end
  end
end