module Datadog
  module CI
    module TestRetries
      class Component
        attr_reader retry_failed_tests_enabled: bool

        attr_reader retry_failed_tests_max_attempts: Integer

        attr_reader retry_failed_tests_total_limit: Integer

        attr_reader retry_failed_tests_count: Integer

        attr_reader retry_new_tests_enabled: bool

        @mutex: Thread::Mutex

        def initialize: (retry_failed_tests_enabled: bool, retry_failed_tests_max_attempts: Integer, retry_failed_tests_total_limit: Integer, retry_new_tests_enabled: bool) -> void

        def configure: (Datadog::CI::Remote::LibrarySettings library_settings) -> void

        def with_retries: () { () -> void } -> void

        def build_strategy: (Datadog::CI::Test test) -> Datadog::CI::TestRetries::Strategy::Base

        private

        def should_retry_failed_test?: (Datadog::CI::Test test) -> bool

        def test_visibility_component: () -> Datadog::CI::TestVisibility::Component
      end
    end
  end
end
