services:
  # MRI
  datadog-ci-2.7:
    image: ghcr.io/datadog/images-rb/engines/ruby:2.7
    working_dir: /app
    command: /bin/bash
    env_file: ./.env
    environment:
      BUNDLE_GEMFILE: /app/Gemfile-2.7
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - bundle-2.7:/usr/local/bundle
  datadog-ci-3.0:
    image: ghcr.io/datadog/images-rb/engines/ruby:3.0
    working_dir: /app
    command: /bin/bash
    env_file: ./.env
    environment:
      BUNDLE_GEMFILE: /app/Gemfile-3.0
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - bundle-3.0:/usr/local/bundle
  datadog-ci-3.1:
    image: ghcr.io/datadog/images-rb/engines/ruby:3.1
    working_dir: /app
    command: /bin/bash
    env_file: ./.env
    environment:
      BUNDLE_GEMFILE: /app/Gemfile-3.1
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - bundle-3.1:/usr/local/bundle
  datadog-ci-3.2:
    image: ghcr.io/datadog/images-rb/engines/ruby:3.2
    working_dir: /app
    command: /bin/bash
    env_file: ./.env
    environment:
      BUNDLE_GEMFILE: /app/Gemfile-3.2
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - bundle-3.2:/usr/local/bundle
  datadog-ci-3.3:
    image: ghcr.io/datadog/images-rb/engines/ruby:3.3
    working_dir: /app
    command: /bin/bash
    env_file: ./.env
    environment:
      BUNDLE_GEMFILE: /app/Gemfile-3.3
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - bundle-3.3:/usr/local/bundle
  datadog-ci-3.4:
    image: ghcr.io/datadog/images-rb/engines/ruby:3.4
    working_dir: /app
    command: /bin/bash
    env_file: ./.env
    environment:
      BUNDLE_GEMFILE: /app/Gemfile-3.4
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - bundle-3.4:/usr/local/bundle
  # ADD NEW RUBIES HERE
  datadog-ci-jruby-9.4:
    image: ghcr.io/datadog/images-rb/engines/jruby:9.4
    working_dir: /app
    command: /bin/bash
    env_file: ./.env
    environment:
      BUNDLE_GEMFILE: /app/Gemfile-jruby-9.4
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - bundle-jruby-9.4:/usr/local/bundle
volumes:
  bundle-2.7:
  bundle-3.0:
  bundle-3.1:
  bundle-3.2:
  bundle-3.3:
  bundle-3.4:
  bundle-jruby-9.4: # ADD NEW RUBIES HERE
