target :lib do
  signature "sig"

  check "lib"

  ignore "lib/datadog/ci/configuration/settings.rb"

  library "pathname"
  library "json"
  library "logger"
  library "date"
  library "minitest"
  library "net-http"
  library "zlib"
  library "securerandom"
  library "tmpdir"
  library "fileutils"
  library "socket"
  library "optparse"

  repo_path "vendor/rbs"
  library "ddtrace"
  library "gem"
  library "open3"
  library "rspec"
  library "cucumber"
  library "msgpack"
  library "ci_queue"
  library "knapsack_pro"
  library "bundler"
  library "selenium-webdriver"
  library "capybara"
  library "timecop"
  library "webmock"
  library "simplecov"
  library "cuprite"
  library "parallel_tests"
  library "rails"
end
