module Datadog
  module CI
    module Contrib
      module Instrumentation
        class InvalidIntegrationError < StandardError
        end

        self.@registry: Hash[Symbol, untyped]

        self.@configure_once: Datadog::Core::Utils::OnlyOnce

        def self.registry: () -> Hash[Symbol, untyped]

        def self.auto_instrument: () -> void

        def self.instrument: (Symbol integration_name, ?::Hash[untyped, untyped] options) { (?) -> untyped } -> void

        def self.instrument_on_session_start: () -> void

        def self.fetch_integration: (Symbol name) -> untyped

        def self.integration_name: (Class) -> Symbol

        def self.register_integration: (Class integration) -> void

        def self.patch_integration: (Contrib::Integration integration, ?with_dependencies: bool) -> void

        def self.fetch_auto_instrumented_integrations: () -> Array[Contrib::Integration]

        def self.auto_configure_datadog: () -> void

        def self.configure_once: () -> Datadog::Core::Utils::OnlyOnce
      end
    end
  end
end
