module Datadog
  module CI
    module Contrib
      class Integration
        def self.inherited: (untyped) -> void

        def version: () -> untyped

        def available?: () -> bool

        def loaded?: () -> bool

        def compatible?: () -> bool

        def patchable?: () -> bool

        def configuration: () -> Datadog::CI::Contrib::Settings

        def configure: (?::Hash[Symbol, untyped] options) ?{ (Datadog::CI::Contrib::Settings) -> Datadog::CI::Contrib::Settings } -> Datadog::CI::Contrib::Settings

        def enabled: () -> bool

        def patcher: () -> untyped

        def patched?: () -> bool?

        def patch: () -> Hash[Symbol, bool]

        def dependants: () -> Array[Symbol]

        def late_instrument?: () -> bool

        def new_configuration: () -> Datadog::CI::Contrib::Settings
      end
    end
  end
end
