module Datadog
  module CI
    module Contrib
      module Patcher
        def self.included: (Class base) -> void

        module CommonMethods
          attr_accessor patch_error_result: Hash[Symbol, untyped]

          attr_accessor patch_successful: bool

          def patch_name: () -> String?

          def name: () -> String

          def patched?: () -> bool

          def patch: () -> void

          def on_patch_error: (StandardError e) -> Hash[Symbol, untyped]

          private

          def patch_only_once: () -> Datadog::Core::Utils::OnlyOnce

          @patch_only_once: Datadog::Core::Utils::OnlyOnce
        end
      end
    end
  end
end
