module Datadog
  module CI
    module Contrib
      class Settings
        type option_value = bool | Integer | String | nil

        include Core::Configuration::Base
        extend Datadog::Core::Configuration::Options::ClassMethods
        include Datadog::Core::Configuration::Options::InstanceMethods

        extend Datadog::Core::Configuration::Base::ClassMethods

        def configure: (?::Hash[Symbol, untyped] options) ?{ (Datadog::CI::Contrib::Settings) -> Datadog::CI::Contrib::Settings } -> Datadog::CI::Contrib::Settings?

        def []: (Symbol name) -> option_value

        def []=: (Symbol name, option_value value) -> option_value

        # default configuration options
        #
        def enabled: () -> bool
        def service_name: () -> String
      end
    end
  end
end
