module Datadog
  module CI
    module Contrib
      module ParallelTests
        module Runner
          def self.included: (untyped base) -> void

          module InstanceMethods : ParallelTests::Test::Runner
            def execute_command: (untyped cmd, untyped process_number, untyped num_processes, Hash[Symbol, untyped] options) -> untyped
            def test_visibility_component: () -> Datadog::CI::TestVisibility::Component
          end
        end
      end
    end
  end
end