version: 2.1
jobs:
  build:
    docker:
      - image: ruby:2.7.5
    steps:
      - checkout
      - run:
          name: Run the default task
          command: |
            gem install bundler -v 2.3.26
            bundle install
            bundle exec rake
