module Datadog
  module CI
    module TestRetries
      module Strategy
        class RetryFlakeDetection < Base
          @enabled: bool

          @total_limit: Integer

          @retried_count: Integer

          @max_attempts_thresholds: Datadog::CI::Remote::SlowTestRetries

          DEFAULT_TOTAL_TESTS_COUNT: 100

          attr_reader enabled: bool

          attr_reader max_attempts_thresholds: Datadog::CI::Remote::SlowTestRetries

          attr_reader total_limit: Integer

          attr_reader retried_count: Integer

          def initialize: (enabled: bool) -> void

          def covers?: (Datadog::CI::Test test_span) -> bool

          def configure: (Datadog::CI::Remote::LibrarySettings library_settings, Datadog::CI::TestSession test_session) -> void

          def build_driver: (Datadog::CI::Test test_span) -> Datadog::CI::TestRetries::Driver::Base

          private

          def mark_test_session_faulty: (Datadog::CI::TestSession? test_session) -> void

          def set_max_attempts_thresholds: (Datadog::CI::Remote::LibrarySettings) -> void

          def calculate_total_retries_limit: (Datadog::CI::Remote::LibrarySettings, Datadog::CI::TestSession) -> void
        end
      end
    end
  end
end
