# frozen_string_literal: true

source "https://rubygems.org"

gem "pry"
gem "rspec"
gem "rake"
gem "cucumber", "~> 7"
gem "datadog", git: "https://github.com/DataDog/dd-trace-rb.git", branch: "master"
gem "datadog-ci", path: "/vendor/datadog-ci"
