# frozen_string_literal: true

source "https://rubygems.org"

gem "pry"
gem "rspec"
gem "rake"
gem "cucumber", "~> 7"
gem "ddtrace"

gem "datadog-ci", path: "/vendor/datadog-ci"
gem "datadog", github: "Datadog/dd-trace-rb", branch: "2.0"
