module Datadog
  module CI
    module Contrib
      module Minitest
        module Ext
          ENV_ENABLED: String

          FRAMEWORK: String

          DEFAULT_SERVICE_NAME: String
        end
      end
    end
  end
end
