module Datadog
  module CI
    module Contrib
      module Minitest
        module Ext
          ENV_ENABLED: String

          FRAMEWORK: String

          DEFAULT_SERVICE_NAME: String

          STEP_SPAN_TYPE: String
          BEFORE_STEP_SPAN_NAME: String
          AFTER_STEP_SPAN_NAME: String
        end
      end
    end
  end
end
