module Datadog
  module CI
    module Contrib
      module Minitest
        module Helpers
          def self.start_test_suite: (untyped klass) -> Datadog::CI::TestSuite?

          def self.test_suite_name: (untyped klass, String? method_name) -> ::String

          def self.parallel?: (untyped klass) -> bool

          def self.extract_source_location_from_class: (untyped klass) -> Array[::String]
        end
      end
    end
  end
end
