module Datadog
  module CI
    module Contrib
      module Minitest
        module Plugin
          def self.included: (untyped base) -> untyped

          class DatadogReporter < ::Minitest::AbstractReporter
            @reporter: WeakRef

            def initialize: (Minitest::AbstractReporter reporter) -> void
          end

          module ClassMethods
            def plugin_datadog_ci_init: (*untyped) -> (nil | untyped)

            def initialize: (untyped reporter) -> void

            def report: () -> (nil | untyped)

            def reporter: () -> Minitest::CompositeReporter

            private

            def datadog_configuration: () -> untyped
          end
        end
      end
    end
  end
end
