module Datadog
  module CI
    module Contrib
      module Minitest
        module Reporter
          def self.included: (untyped base) -> untyped

          module InstanceMethods : ::Minitest::AbstractReporter
            def report: (*untyped) -> untyped

            private

            def datadog_configuration: () -> Datadog::CI::Contrib::Minitest::Configuration::Settings
          end
        end
      end
    end
  end
end
