module Datadog
  module CI
    module Contrib
      module Minitest
        module RunMethodCapture
          interface _Storage
            def _dd_pre_datadog_minitest_run: () -> UnboundMethod?

            def _dd_pre_datadog_minitest_run=: (UnboundMethod? method) -> UnboundMethod?
          end

          def self.capture_concrete_pre_datadog_run!: (_Storage storage, untyped owner, Module datadog_run_owner) -> void

          def self.concrete_pre_datadog_run?: (UnboundMethod? method, Module datadog_run_owner) -> bool?
        end
      end
    end
  end
end
