module Datadog
  module CI
    module Contrib
      module Minitest
        module Runner
          def self.included: (untyped base) -> untyped

          module ClassMethods : ::Minitest
            def init_plugins: (*untyped) -> (nil | untyped)

            def run_one_method: (untyped klass, String method_name) -> untyped

            private

            def datadog_integration: () -> Datadog::CI::Contrib::Integration

            def datadog_configuration: () -> untyped

            def test_visibility_component: () -> Datadog::CI::TestVisibility::Component

            def test_retries_component: () -> Datadog::CI::TestRetries::Component
          end
        end
      end
    end
  end
end
