module Datadog
  module CI
    module Contrib
      module Minitest
        module Runner
          def self.included: (untyped base) -> untyped

          module ClassMethods : ::Minitest
            def init_plugins: (*untyped) -> (nil | untyped)

            def run_one_method: (untyped klass, String method_name) -> untyped

            def old_run_one_method: (untyped klass, String method_name) -> untyped

            def run: (*untyped) -> untyped

            private

            def datadog_integration: () -> Datadog::CI::Contrib::Integration

            def datadog_configuration: () -> untyped

            def test_tracing_component: () -> Datadog::CI::TestTracing::Component

            def test_retries_component: () -> Datadog::CI::TestRetries::Component

            def test_discovery_component: () -> (Datadog::CI::TestDiscovery::Component | Datadog::CI::TestDiscovery::NullComponent)

            def discover_tests: () -> void
          end
        end
      end
    end
  end
end
