module Datadog
  module CI
    module Contrib
      module Minitest
        module Test
          module ClassMethods
            @datadog_itr_unskippable_suite: bool
            @datadog_itr_unskippable_tests: Array[String]?

            def datadog_itr_unskippable: (*untyped) -> void

            def dd_suite_unskippable?: () -> bool

            def dd_test_unskippable?: (String test_name) -> bool
          end

          module InstanceMethods : ::Minitest::Test
            include ::Minitest::Test::LifecycleHooks
            extend ClassMethods

            def before_setup: () -> (nil | untyped)

            def after_teardown: () -> untyped

            private

            def datadog_integration: () -> Datadog::CI::Contrib::Integration

            def datadog_configuration: () -> untyped

            def test_visibility_component: () -> Datadog::CI::TestVisibility::Component

            def finish_with_result: (Datadog::CI::Span? span, String result_code) -> void
          end
        end
      end
    end
  end
end
