module Datadog
  module CI
    module Contrib
      module Minitest
        module Test
          @_dd_pre_datadog_minitest_run: untyped

          def self._dd_pre_datadog_minitest_run: () -> untyped

          def self._dd_pre_datadog_minitest_run=: (untyped) -> untyped

          module ClassMethods
            include Datadog::CI::Contrib::Minitest::Helpers::_RunnableClass

            def method_added: (Symbol method_name) -> untyped
          end

          module InstanceMethods : ::Minitest::Test
            include ::Minitest::Test::LifecycleHooks
            extend ClassMethods

            def run: () -> ::Minitest::Result

            def after_teardown: () -> untyped

            private

            def datadog_run_reentered?: () -> bool

            def run_without_datadog_reentry: () -> ::Minitest::Result

            def start_datadog_test_suite_if_parallel: () -> Datadog::CI::TestSuite?

            def start_datadog_test: () -> Datadog::CI::Test?

            def skip_datadog_suite: (Datadog::CI::TestSuite test_suite) -> ::Minitest::Result

            def skip_datadog_test: (Datadog::CI::Test test_span) -> ::Minitest::Result

            def datadog_integration: () -> Datadog::CI::Contrib::Integration

            def datadog_configuration: () -> Datadog::CI::Contrib::Minitest::Configuration::Settings

            def _dd_test_tracing_component: () -> Datadog::CI::TestTracing::Component

            def finish_with_result: (Datadog::CI::Span? span, String result_code) -> void
          end
        end
      end
    end
  end
end
