module Datadog
  module CI
    module Remote
      class Component
        include Datadog::CI::Utils::Stateful

        FILE_STORAGE_KEY: String

        @library_settings_client: Datadog::CI::Remote::LibrarySettingsClient
        @library_configuration: Datadog::CI::Remote::LibrarySettings

        def initialize: (library_settings_client: Datadog::CI::Remote::LibrarySettingsClient) -> void

        def configure: (Datadog::CI::TestSession test_session) -> void

        # Implementation of Stateful interface
        def serialize_state: () -> Hash[Symbol, untyped]

        def restore_state: (Hash[Symbol, untyped] state) -> void

        def storage_key: () -> String

        private

        def test_management: () -> Datadog::CI::TestManagement::Component

        def test_visibility: () -> Datadog::CI::TestVisibility::Component

        def test_optimisation: () -> Datadog::CI::TestOptimisation::Component

        def test_retries: () -> Datadog::CI::TestRetries::Component

        def git_tree_upload_worker: () -> Datadog::CI::Worker

        def impacted_tests_detection: () -> Datadog::CI::ImpactedTestsDetection::Component
      end
    end
  end
end
