module Datadog
  module CI
    module CLI
      module Command
        class SkippableTestsPercentageEstimate < Base
          private

          def build_action: () -> untyped
        end
      end
    end
  end
end
