module Datadog
  module CI
    module TestRetries
      module Driver
        class Base
          def should_retry?: () -> bool

          def mark_as_retry: (Datadog::CI::Test test_span) -> void

          def record_retry: (Datadog::CI::Test test_span) -> void

          def record_duration: (Float duration) -> void

          def retry_reason: () -> String
        end
      end
    end
  end
end
