module Datadog
  module CI
    module TestRetries
      module Driver
        class RetryFlakeDetection < Base
          @max_attempts_thresholds: Datadog::CI::Remote::SlowTestRetries

          @attempts: Integer
          @max_attempts: Integer

          def initialize: (Datadog::CI::Test test_span, max_attempts_thresholds: Datadog::CI::Remote::SlowTestRetries) -> void
        end
      end
    end
  end
end
