module Datadog
  module CI
    module Ext
      module AppTypes
        TYPE_TEST: "test"
        TYPE_TEST_SESSION: "test_session_end"
        TYPE_TEST_MODULE: "test_module_end"
        TYPE_TEST_SUITE: "test_suite_end"

        CI_SPAN_TYPES: Array[String]
      end
    end
  end
end
