module Datadog
  module CI
    module Ext
      module AppTypes
        TYPE_TEST: "test"
        TYPE_TEST_SESSION: "test_session_end"

        CI_SPAN_TYPES: Array[String]
      end
    end
  end
end
