module Datadog
  module CI
    module Ext
      module DDTest
        PLAN_FOLDER: String
        TESTOPTIMIZATION_CACHE_PATH: String
        SETTINGS_FILE_NAME: String
        KNOWN_TESTS_FILE_NAME: String
        TEST_MANAGEMENT_TESTS_FILE_NAME: String
        SKIPPABLE_TESTS_FILE_NAME: String
      end
    end
  end
end
