module Datadog
  module CI
    module Ext
      module Providers
        TAG_JOB_NAME: "ci.job.name"

        TAG_JOB_URL: "ci.job.url"

        TAG_PIPELINE_ID: "ci.pipeline.id"

        TAG_PIPELINE_NAME: "ci.pipeline.name"

        TAG_PIPELINE_NUMBER: "ci.pipeline.number"

        TAG_PIPELINE_URL: "ci.pipeline.url"

        TAG_PROVIDER_NAME: "ci.provider.name"

        TAG_STAGE_NAME: "ci.stage.name"

        TAG_WORKSPACE_PATH: "ci.workspace_path"

        TAG_NODE_LABELS: "ci.node.labels"

        TAG_NODE_NAME: "ci.node.name"

        TAG_CI_ENV_VARS: "_dd.ci.env_vars"
      end
    end
  end
end
