module Datadog
  module CI
    module Ext
      module Settings
        ENV_MODE_ENABLED: String
        ENV_AGENTLESS_MODE_ENABLED: String
        ENV_AGENTLESS_URL: String
        ENV_EXPERIMENTAL_TEST_SUITE_LEVEL_VISIBILITY_ENABLED: String
        ENV_USE_TEST_LEVEL_VISIBILITY: String

        DD_SITE_ALLOWLIST: Array[String]
      end
    end
  end
end
