module Datadog
  module CI
    module Ext
      module Test
        CONTEXT_ORIGIN: "ciapp-test"

        TAG_FRAMEWORK: "test.framework"

        TAG_FRAMEWORK_VERSION: "test.framework_version"

        TAG_NAME: "test.name"

        TAG_SKIP_REASON: "test.skip_reason"

        TAG_STATUS: "test.status"

        TAG_SUITE: "test.suite"

        TAG_MODULE: "test.module"

        TAG_TYPE: "test.type"

        TAG_COMMAND: "test.command"

        TAG_SOURCE_FILE: "test.source.file"

        TAG_SOURCE_START: "test.source.start"

        TAG_SOURCE_END: "test.source.end"

        TAG_CODEOWNERS: "test.codeowners"

        TAG_PARAMETERS: "test.parameters"

        TAG_ITR_TEST_SKIPPING_ENABLED: "test.itr.tests_skipping.enabled"

        TAG_ITR_TEST_SKIPPING_TYPE: "test.itr.tests_skipping.type"

        TAG_ITR_TEST_SKIPPING_COUNT: "test.itr.tests_skipping.count"

        TAG_ITR_SKIPPED_BY_ITR: "test.skipped_by_itr"

        TAG_ITR_TESTS_SKIPPED: "_dd.ci.itr.tests_skipped"

        TAG_ITR_UNSKIPPABLE: "test.itr.unskippable"

        TAG_ITR_FORCED_RUN: "test.itr.forced_run"

        TAG_CODE_COVERAGE_ENABLED: "test.code_coverage.enabled"

        TAG_TEST_SESSION_ID: "_test.session_id"

        TAG_TEST_MODULE_ID: "_test.module_id"

        TAG_TEST_SUITE_ID: "_test.suite_id"

        TAG_TEST_IS_MODIFIED: "test.is_modified"

        TRANSIENT_TAGS: Array[String]

        INHERITABLE_TAGS: Array[String]

        TAG_OS_ARCHITECTURE: "os.architecture"

        TAG_OS_PLATFORM: "os.platform"

        TAG_OS_VERSION: "os.version"

        TAG_RUNTIME_NAME: "runtime.name"

        TAG_RUNTIME_VERSION: "runtime.version"

        TAG_SPAN_KIND: "span.kind"

        SPAN_KIND_TEST: "test"

        ITR_TEST_SKIPPING_MODE: "test"

        ITR_UNSKIPPABLE_OPTION: :datadog_itr_unskippable

        TAG_IS_RUM_ACTIVE: "test.is_rum_active"

        TAG_BROWSER_DRIVER: "test.browser.driver"

        TAG_BROWSER_DRIVER_VERSION: "test.browser.driver_version"

        TAG_BROWSER_NAME: "test.browser.name"

        TAG_BROWSER_VERSION: "test.browser.version"

        TAG_IS_RETRY: "test.is_retry"

        TAG_RETRY_REASON: "test.retry_reason"

        TAG_IS_NEW: "test.is_new"

        TAG_EARLY_FLAKE_ENABLED: "test.early_flake.enabled"

        TAG_EARLY_FLAKE_ABORT_REASON: "test.early_flake.abort_reason"

        EARLY_FLAKE_FAULTY: "faulty"

        TAG_TEST_SESSION_NAME: "test_session.name"

        TAG_USER_PROVIDED_TEST_SERVICE: "_dd.test.is_user_provided_service"

        METRIC_CPU_COUNT: "_dd.host.vcpu_count"

        TAG_CODE_COVERAGE_LINES_PCT: "test.code_coverage.lines_pct"

        TAG_TEST_MANAGEMENT_ENABLED: "test.test_management.enabled"

        TAG_IS_ATTEMPT_TO_FIX: "test.test_management.is_attempt_to_fix"

        TAG_IS_TEST_DISABLED: "test.test_management.is_test_disabled"

        TAG_IS_QUARANTINED: "test.test_management.is_quarantined"

        TAG_HAS_FAILED_ALL_RETRIES: "test.has_failed_all_retries"

        TAG_ATTEMPT_TO_FIX_PASSED: "test.test_management.attempt_to_fix_passed"

        module LibraryCapabilities
          TAG_TEST_IMPACT_ANALYSIS: "_dd.library_capabilities.test_impact_analysis"
          TAG_EARLY_FLAKE_DETECTION: "_dd.library_capabilities.early_flake_detection"
          TAG_AUTO_TEST_RETRIES: "_dd.library_capabilities.auto_test_retries"
          TAG_TEST_MANAGEMENT_QUARANTINE: "_dd.library_capabilities.test_management.quarantine"
          TAG_TEST_MANAGEMENT_DISABLE: "_dd.library_capabilities.test_management.disable"
          TAG_TEST_MANAGEMENT_ATTEMPT_TO_FIX: "_dd.library_capabilities.test_management.attempt_to_fix"

          module Versions
            TEST_IMPACT_ANALYSIS_VERSION: String
            EARLY_FLAKE_DETECTION_VERSION: String
            AUTO_TEST_RETRIES_VERSION: String
            TEST_MANAGEMENT_QUARANTINE_VERSION: String
            TEST_MANAGEMENT_DISABLE_VERSION: String
            TEST_MANAGEMENT_ATTEMPT_TO_FIX_VERSION: String
          end

          CAPABILITY_VERSIONS: Hash[String, String]
        end

        module Status
          PASS: "pass"

          FAIL: "fail"

          SKIP: "skip"
        end

        module ExecutionStatsStatus
          FAIL_IGNORED: "fail_ignored"
        end

        module Type
          TEST: "test"

          BROWSER: "browser"

          BENCHMARK: "benchmark"
        end

        module RetryReason
          RETRY_DETECT_FLAKY: "early_flake_detection"

          RETRY_FAILED: "auto_test_retries"

          RETRY_FLAKY_FIXED: "attempt_to_fix"

          RETRY_EXTERNAL: "external"
        end

        module SkipReason
          TEST_IMPACT_ANALYSIS: "Skipped by Datadog's Test Impact Analysis"
          TEST_MANAGEMENT_DISABLED: "Flaky test is disabled by Datadog"
        end
      end
    end
  end
end
