module Datadog
  module CI
    class ConcurrentSpan < Span
      @mutex: Thread::Mutex

      def initialize: (Datadog::Tracing::SpanOperation tracer_span) -> void
      def passed!: () -> void
      def failed!: (?exception: untyped?) -> void
      def skipped!: (?exception: untyped?, ?reason: String?) -> void
      def get_tag: (String key) -> untyped?
      def set_tag: (String key, untyped? value) -> void
      def set_metric: (String key, untyped value) -> void
      def finish: () -> void
      def set_tags: (Hash[untyped, untyped] tags) -> void

      def set_environment_runtime_tags: () -> void

      def set_default_tags: () -> void

      def synchronize: () { () -> untyped } -> untyped
    end
  end
end
