module Datadog
  module CI
    class NullSpan < Span
      def initialize: () -> void

      def id: () -> nil

      def name: () -> nil

      def service: () -> nil

      def span_type: () -> nil

      def passed!: () -> nil

      def failed!: (?exception: untyped?) -> nil

      def skipped!: (?exception: untyped?, ?reason: untyped?) -> nil

      def get_tag: (untyped key) -> nil

      def set_tag: (untyped key, untyped value) -> nil

      def set_metric: (untyped key, untyped value) -> nil

      def finish: () -> nil

      def set_tags: (untyped tags) -> nil

      def set_environment_runtime_tags: () -> nil

      def set_default_tags: () -> nil

      def to_s: () -> untyped
    end
  end
end
