module Datadog
  module CI
    module Recorder
      self.@environment_tags: Hash[String, String]

      def self.trace_test: (String span_name, ?service_name: String?, ?operation_name: String, ?tags: Hash[untyped, untyped]) ?{ (Datadog::CI::Test span) -> untyped } -> untyped

      def self.trace: (String span_type, String span_name) ?{ (Datadog::CI::Span span) -> untyped } -> untyped

      def self.set_tags!: (Datadog::Tracing::TraceOperation trace, Datadog::Tracing::SpanOperation span, ?::Hash[untyped, untyped] tags)  -> untyped

      def self.set_environment_runtime_tags!: (Datadog::Tracing::SpanOperation span) -> untyped
    end
  end
end
