module Datadog
  module CI
    class Test < Span
      def finish: () -> void
      def test_suite_id: () -> String?
      def test_suite_name: () -> String?
      def test_module_id: () -> String?
      def test_session_id: () -> String?
    end
  end
end
