module Datadog
  module CI
    class TestSuite < ConcurrentSpan
      @execution_stats_per_test: Hash[String, Hash[String, Integer]]
      @final_statuses_per_test: Hash[String, String]
      @expected_tests_set: Set[String]

      def record_test_result: (String test_id, String datadog_test_status) -> void

      def record_test_final_status: (String test_id, String final_status) -> void

      def any_passed?: () -> bool

      def test_executed?: (String test_id) -> bool

      def any_test_retry_passed?: (String) -> bool

      def all_executions_failed?: (String) -> bool

      def all_executions_passed?: (String) -> bool

      def set_expected_tests!: (Enumerable[String] tests) -> void

      def expected_test_done!: (String test_name) -> void

      private

      def set_status_from_stats!: () -> void
    end
  end
end
