module Datadog
  module CI
    class Test < Span
      @datadog_test_id: String

      def datadog_test_id: () -> String
      def finish: () -> void
      def test_suite: () -> Datadog::CI::TestSuite?
      def test_suite_id: () -> String?
      def test_suite_name: () -> String?
      def test_module_id: () -> String?
      def test_session_id: () -> String?
      def skipped_by_itr?: () -> bool
      def itr_unskippable!: () -> void
      def parameters: () -> String?
      def is_retry?: () -> bool
      def is_new?: () -> bool
      def any_retry_passed?: () -> bool
      def quarantined?: () -> bool
      def disabled?: () -> bool
      def should_ignore_failures?: () -> bool

      private

      def record_test_result: (String datadog_status) -> void
    end
  end
end
