module Datadog
  module CI
    class Test < Span
      def finish: () -> void
      def test_suite: () -> Datadog::CI::TestSuite?
      def test_suite_id: () -> String?
      def test_suite_name: () -> String?
      def test_module_id: () -> String?
      def test_session_id: () -> String?
      def skipped_by_itr?: () -> bool
      def source_file: () -> String?
      def parameters: () -> String?

      private

      def record_test_result: (String datadog_status) -> void
    end
  end
end
