module Datadog
  module CI
    class TestSuite < ConcurrentSpan
      @execution_stats_per_test: Hash[String, Hash[String, Integer]]

      def record_test_result: (String test_id, String datadog_test_status) -> void

      def any_passed?: () -> bool

      private

      def set_status_from_stats!: () -> void

      def derive_test_status_from_execution_stats: (Hash[String, Integer] test_stats) -> String
    end
  end
end
