module Datadog
  module CI
    class TestSession < ConcurrentSpan
      attr_accessor estimated_total_tests_count: Integer
      attr_accessor distributed: bool

      @inheritable_tags: Hash[untyped, untyped]

      def inheritable_tags: () -> Hash[untyped, untyped]

      def test_command: () -> String?

      def ci_provider: () -> String?

      def ci_job_name: () -> String?

      def git_commit_message: () -> String?

      def skipping_tests?: () -> bool

      def code_coverage?: () -> bool
    end
  end
end
