module Datadog
  module CI
    class TestSession < ConcurrentSpan
      attr_accessor total_tests_count: Integer
      @inheritable_tags: Hash[untyped, untyped]

      def inheritable_tags: () -> Hash[untyped, untyped]
    end
  end
end
