module Datadog
  module CI
    class Worker < Datadog::Core::Worker
      include Datadog::Core::Workers::Async::Thread
      include Datadog::Core::Workers::Async::Thread::PrependedMethods

      DEFAULT_SHUTDOWN_TIMEOUT: 60

      DEFAULT_WAIT_TIMEOUT: 60

      def stop: (?Integer timeout) -> void

      def wait_until_done: (?Integer timeout) -> void

      def done?: () -> bool
    end

    class DummyWorker < Worker
      def initialize: () -> void
    end
  end
end
