module Datadog
  module CI
    module Contrib
      module RSpec
        module Example
          def self.included: (untyped base) -> untyped
          module InstanceMethods : ::RSpec::Core::Example
            @skip_reporting: bool

            @datadog_test_suite_description: String

            @datadog_test_name: String
            @datadog_test_suite_name: String
            @datadog_test_parameters: String

            def run: (untyped example_group_instance, untyped reporter) -> untyped

            private

            def fetch_top_level_example_group: () -> Hash[Symbol, untyped]
            def datadog_integration: () -> Datadog::CI::Contrib::Integration
            def datadog_configuration: () -> untyped
            def test_visibility_component: () -> Datadog::CI::TestVisibility::Component
            def test_retries_component: () -> Datadog::CI::TestRetries::Component
            def ci_queue?: () -> bool

            def datadog_test_suite_description: () -> String
            def datadog_test_name: () -> String
            def datadog_test_suite_name: () -> String
            def datadog_test_parameters: () -> String
            def datadog_unskippable?: () -> bool
          end
        end
      end
    end
  end
end
