module Datadog
  module CI
    module Contrib
      module RSpec
        module ExampleGroup
          def self.included: (untyped base) -> untyped

          module ClassMethods
            include ::RSpec::Core::ExampleGroup::ClassMethods

            def run: (?untyped reporter) -> untyped

            private

            def all_examples_skipped_by_datadog?: () -> bool

            def datadog_configuration: () -> untyped

            def test_visibility_component: () -> Datadog::CI::TestVisibility::Component?

            def test_optimisation_component: () -> (Datadog::CI::TestOptimisation::Component | Datadog::CI::TestOptimisation::NullComponent)

            def test_management_component: () -> Datadog::CI::TestManagement::Component?
          end
        end
      end
    end
  end
end
