module Datadog
  module CI
    module Contrib
      module RSpec
        module Ext
          ENV_ENABLED: String
          ENV_DATADOG_FORMATTER_ENABLED: String

          FRAMEWORK: String
          DEFAULT_SERVICE_NAME: String

          METADATA_DD_RETRIES: Symbol
          METADATA_DD_RETRY_RESULTS: Symbol
          METADATA_DD_RETRY_REASON: Symbol
          METADATA_DD_QUARANTINED: Symbol
          METADATA_DD_DISABLED: Symbol
          METADATA_DD_SKIPPED_BY_ITR: Symbol
        end
      end
    end
  end
end
