module Datadog
  module CI
    module Contrib
      module RSpec
        module Ext
          ENV_ENABLED: String

          FRAMEWORK: String
          DEFAULT_SERVICE_NAME: String

          OPERATION_NAME: String
          ENV_OPERATION_NAME: String

          TEST_MODULE_NAME: String
        end
      end
    end
  end
end
