module Datadog
  module CI
    module Contrib
      module RSpec
        class Integration < Datadog::CI::Contrib::Integration
          MINIMUM_VERSION: Gem::Version

          def version: () -> untyped

          def loaded?: () -> untyped

          def compatible?: () -> bool

          def late_instrument?: () -> false

          def new_configuration: () -> untyped

          def patcher: () -> untyped

          def test_discovery_component: () -> Datadog::CI::TestDiscovery::Component
        end
      end
    end
  end
end
