module Datadog
  module CI
    module Contrib
      module RSpec
        module Patcher
          include Datadog::Tracing::Contrib::Patcher

          def self?.target_version: () -> String

          def self?.patch: () -> void

          def self?.ci_queue?: () -> bool

          def self?.knapsack_pro?: () -> bool
        end
      end
    end
  end
end
