module Datadog
  module CI
    module Contrib
      module RSpec
        module Runner
          def self.included: (untyped base) -> untyped

          module InstanceMethods : ::RSpec::Core::Runner
            def run_specs: (untyped example_groups) -> untyped

            private

            def datadog_configuration: () -> untyped

            def test_visibility_component: () -> Datadog::CI::TestVisibility::Component
          end
        end
      end
    end
  end
end
