module Datadog
  module CI
    module Contrib
      module RSpec
        module Runner
          def self.included: (untyped base) -> untyped

          module InstanceMethods : ::RSpec::Core::Runner
            def run_specs: (*untyped) -> untyped

            private

            def datadog_integration: () -> Datadog::CI::Contrib::Integration

            def datadog_configuration: () -> untyped

            def test_tracing_component: () -> Datadog::CI::TestTracing::Component

            def test_discovery_component: () -> (Datadog::CI::TestDiscovery::Component | Datadog::CI::TestDiscovery::NullComponent | nil)

            def discover_tests: (Datadog::CI::TestDiscovery::Component | Datadog::CI::TestDiscovery::NullComponent) -> void
          end
        end
      end
    end
  end
end
