module Datadog
  module CI
    module Contrib
      module RSpec
        module Runner
          def self.included: (untyped base) -> untyped

          module InstanceMethods : ::RSpec::Core::Runner
            def run_specs: (*untyped) -> untyped

            private

            def datadog_integration: () -> Datadog::CI::Contrib::Integration

            def datadog_configuration: () -> untyped

            def test_visibility_component: () -> Datadog::CI::TestVisibility::Component

            def test_discovery_component: () -> Datadog::CI::TestDiscovery::Component

            def discover_tests: () -> void
          end
        end
      end
    end
  end
end
