module Datadog
  module CI
    module Codeowners
      class Matcher
        @rules: Array[Rule]

        def initialize: (String codeowners_file_path) -> void

        def list_owners: (String file_path) -> Array[String]

        private

        def parse: (String file_path) -> Array[Rule]

        def comment?: (String line) -> bool

        def section?: (String line) -> bool

        def expand_pattern: (String pattern) -> String
      end
    end
  end
end
