module Datadog
  module CI
    module ITR
      class Runner
        @enabled: bool
        @client: Datadog::CI::ITR::Client

        def initialize: (?enabled: bool, api: Datadog::CI::Transport::Api::Base?) -> void

        def enabled?: () -> bool

        def configure: (service: String?) -> void
      end
    end
  end
end
