module Datadog
  module CI
    module TestOptimisation
      module Telemetry
        def self.code_coverage_started: (Datadog::CI::Test test) -> void

        def self.code_coverage_finished: (Datadog::CI::Test test) -> void

        def self.code_coverage_is_empty: () -> void

        def self.code_coverage_files: (Integer count) -> void

        def self.code_coverage_errors: () -> void

        def self.tags_for_test: (Datadog::CI::Test test) -> ::Hash[String, String]
      end
    end
  end
end
