module Datadog
  module CI
    module TestTracing
      module Store
        class Execution
          @pid: Integer
          @fiber: Fiber?
          @test: Datadog::CI::Test?

          def initialize: () -> void

          def activate_test: (Datadog::CI::Test test) ?{ () -> untyped } -> void

          def deactivate_test: () -> void

          def active_test: () -> Datadog::CI::Test?
        end
      end
    end
  end
end
