module Datadog
  module CI
    module TestOptimizationCache
      class Component
        READER_BY_MANIFEST_VERSION: Hash[String, singleton(Readers::V1)]

        @locator: Locator
        @reader: Readers::Base

        def initialize: (manifest_file: String?, runfiles_dir: String?, runfiles_manifest_file: String?, test_srcdir: String?) -> void

        def cache_available?: () -> bool

        def load_settings: () -> Hash[String, untyped]?

        def load_known_tests: () -> Hash[String, untyped]?

        def load_test_management: () -> Hash[String, untyped]?

        def load_skippable_tests: () -> Hash[String, untyped]?

        def shutdown!: () -> nil

        private

        def build_reader: () -> Readers::Base
      end
    end
  end
end
