module Datadog
  module CI
    module TestImpactAnalysis
      module Coverage
        class DDCov
          def initialize: (root: String, ignored_path: String?, use_allocation_tracing: bool) -> void

          def start: () -> void

          def stop: () -> Hash[String, untyped]
        end
      end
    end
  end
end
