module Datadog
  module CI
    module TestImpactAnalysis
      module Coverage
        class Files
          EMPTY_FILES: Array[String]

          @coverage: Hash[String, untyped]
          @custom_impacted_files: Array[String]
          @root: String
          @normalized_files: Array[String]?

          def initialize: (Hash[String, untyped] coverage, ?Array[String] custom_impacted_files) -> void

          def each: () { (String file) -> void } -> void

          def size: () -> Integer

          def write_to: (untyped packer) -> untyped

          def inspect_coverage: () -> Hash[String, untyped]

          private

          def normalized_files: () -> Array[String]
        end
      end
    end
  end
end
