module Datadog
  module CI
    module TestManagement
      class Component
        include Datadog::CI::Utils::Stateful

        FILE_STORAGE_KEY: String

        @enabled: bool

        @tests_properties_client: Datadog::CI::TestManagement::TestsProperties

        @tests_properties: Hash[String, Hash[String, bool]]

        attr_reader enabled: bool

        attr_reader tests_properties: Hash[String, Hash[String, bool]]

        def initialize: (enabled: bool, tests_properties_client: Datadog::CI::TestManagement::TestsProperties) -> void

        def configure: (Datadog::CI::Remote::LibrarySettings library_settings, Datadog::CI::TestSession test_session) -> void

        def tag_test_from_properties: (Datadog::CI::Test test) -> void

        def attempt_to_fix?: (String datadog_fqn_test_id) -> bool

        def restore_state_from_datadog_test_runner: () -> bool

        # Implementation of Stateful interface
        def serialize_state: () -> Hash[Symbol, untyped]

        def restore_state: (Hash[Symbol, untyped] state) -> void

        def storage_key: () -> String
      end
    end
  end
end
