module Datadog
  module CI
    module TestManagement
      class NullComponent
        @enabled: untyped

        @tests_properties: untyped

        attr_reader enabled: untyped

        attr_reader tests_properties: untyped

        def initialize: () -> void

        def configure: (untyped _, untyped _) -> nil

        def tag_test_from_properties: (untyped _) -> nil

        def attempt_to_fix?: (String _datadog_fqn_test_id) -> bool

        def disabled?: (String _datadog_fqn_test_id) -> bool
      end
    end
  end
end
