# frozen_string_literal: true

require "set"

# This file is auto-generated from `supported-configurations.json` by `rake local_config_map:generate`.
# Do not change manually! Please refer to `https://github.com/DataDog/dd-trace-rb/blob/master/docs/AccessEnvironmentVariables.md` for more information.

module Datadog
  module CI
    module Configuration
      SUPPORTED_CONFIGURATION_NAMES =
        Set["DD_ACTION_EXECUTION_ID",
          "DD_AGENTLESS_LOG_SUBMISSION_ENABLED",
          "DD_AGENTLESS_LOG_SUBMISSION_URL",
          "DD_CIVISIBILITY_AGENTLESS_ENABLED",
          "DD_CIVISIBILITY_AGENTLESS_URL",
          "DD_CIVISIBILITY_AUTO_INSTRUMENTATION_PROVIDER",
          "DD_CIVISIBILITY_CODE_COVERAGE_REPORT_UPLOAD_ENABLED",
          "DD_CIVISIBILITY_CUPRITE_ENABLED",
          "DD_CIVISIBILITY_EARLY_FLAKE_DETECTION_ENABLED",
          "DD_CIVISIBILITY_ENABLED",
          "DD_CIVISIBILITY_EXPERIMENTAL_TEST_SUITE_LEVEL_VISIBILITY_ENABLED",
          "DD_CIVISIBILITY_FLAKY_RETRY_COUNT",
          "DD_CIVISIBILITY_FLAKY_RETRY_ENABLED",
          "DD_CIVISIBILITY_FORCE_TEST_LEVEL_VISIBILITY",
          "DD_CIVISIBILITY_GIT_METADATA_UPLOAD_ENABLED",
          "DD_CIVISIBILITY_IMPACTED_TESTS_DETECTION_ENABLED",
          "DD_CIVISIBILITY_ITR_CODE_COVERAGE_EXCLUDED_BUNDLE_PATH",
          "DD_CIVISIBILITY_ITR_CODE_COVERAGE_USE_SINGLE_THREADED_MODE",
          "DD_CIVISIBILITY_ITR_ENABLED",
          "DD_CIVISIBILITY_ITR_TEST_IMPACT_ANALYSIS_USE_ALLOCATION_TRACING",
          "DD_CIVISIBILITY_RUM_FLUSH_WAIT_MILLIS",
          "DD_CIVISIBILITY_SELENIUM_ENABLED",
          "DD_CIVISIBILITY_SIMPLECOV_INSTRUMENTATION_ENABLED",
          "DD_CIVISIBILITY_TOTAL_FLAKY_RETRY_COUNT",
          "DD_CI_ACTIVESUPPORT_ENABLED",
          "DD_CI_LOGRAGE_ENABLED",
          "DD_CI_SEMANTIC_LOGGER_ENABLED",
          "DD_CUSTOM_TRACE_ID",
          "DD_GIT_BRANCH",
          "DD_GIT_COMMIT_AUTHOR_DATE",
          "DD_GIT_COMMIT_AUTHOR_EMAIL",
          "DD_GIT_COMMIT_AUTHOR_NAME",
          "DD_GIT_COMMIT_COMMITTER_DATE",
          "DD_GIT_COMMIT_COMMITTER_EMAIL",
          "DD_GIT_COMMIT_COMMITTER_NAME",
          "DD_GIT_COMMIT_HEAD_SHA",
          "DD_GIT_COMMIT_MESSAGE",
          "DD_GIT_COMMIT_SHA",
          "DD_GIT_PULL_REQUEST_BASE_BRANCH",
          "DD_GIT_PULL_REQUEST_BASE_BRANCH_SHA",
          "DD_GIT_REPOSITORY_URL",
          "DD_GIT_TAG",
          "DD_PIPELINE_EXECUTION_ID",
          "DD_TEST_MANAGEMENT_ATTEMPT_TO_FIX_RETRIES",
          "DD_TEST_MANAGEMENT_ENABLED",
          "DD_TEST_OPTIMIZATION_DISCOVERY_ENABLED",
          "DD_TEST_OPTIMIZATION_DISCOVERY_FILE",
          "DD_TEST_OPTIMIZATION_TIA_STATIC_DEPS_COVERAGE_ENABLED",
          "DD_TEST_SESSION_NAME",
          "DD_TEST_VISIBILITY_DRB_SERVER_URI",
          "DD_TRACE_CI_ENABLED",
          "DD_TRACE_CUCUMBER_ENABLED",
          "DD_TRACE_MINITEST_ENABLED",
          "DD_TRACE_PARALLEL_TESTS_ENABLED",
          "DD_TRACE_RSPEC_DATADOG_FORMATTER_ENABLED",
          "DD_TRACE_RSPEC_ENABLED"].freeze

      ALIASES =
        {}.freeze

      DEPRECATIONS =
        Set[]

      ALIAS_TO_CANONICAL =
        {}.freeze
    end
  end
end
