# frozen_string_literal: true

require "set"
require_relative "test"
require_relative "git"
require_relative "environment"

module Datadog
  module CI
    module Ext
      # SDK-owned metadata. Custom tag names outside this set remain writable.
      module Metadata
        # Explicitly whitelist environment fields; custom ci.* and git.* tags belong to individual events.
        SHARED_ENVIRONMENT_TAGS = [
          Environment::TAG_JOB_ID,
          Environment::TAG_JOB_NAME,
          Environment::TAG_JOB_URL,
          Environment::TAG_NODE_LABELS,
          Environment::TAG_NODE_NAME,
          Environment::TAG_PIPELINE_ID,
          Environment::TAG_PIPELINE_NAME,
          Environment::TAG_PIPELINE_DISPLAY_NAME,
          Environment::TAG_PIPELINE_NUMBER,
          Environment::TAG_PIPELINE_URL,
          Environment::TAG_PROVIDER_NAME,
          Environment::TAG_STAGE_NAME,
          Environment::TAG_WORKSPACE_PATH,
          Environment::TAG_CI_ENV_VARS,
          Environment::TAG_PR_NUMBER,
          Git::TAG_BRANCH,
          Git::TAG_TAG,
          Git::TAG_REPOSITORY_URL,
          Git::TAG_COMMIT_SHA,
          Git::TAG_COMMIT_MESSAGE,
          Git::TAG_COMMIT_AUTHOR_NAME,
          Git::TAG_COMMIT_AUTHOR_EMAIL,
          Git::TAG_COMMIT_AUTHOR_DATE,
          Git::TAG_COMMIT_COMMITTER_NAME,
          Git::TAG_COMMIT_COMMITTER_EMAIL,
          Git::TAG_COMMIT_COMMITTER_DATE,
          Git::TAG_COMMIT_HEAD_SHA,
          Git::TAG_COMMIT_HEAD_MESSAGE,
          Git::TAG_COMMIT_HEAD_AUTHOR_NAME,
          Git::TAG_COMMIT_HEAD_AUTHOR_EMAIL,
          Git::TAG_COMMIT_HEAD_AUTHOR_DATE,
          Git::TAG_COMMIT_HEAD_COMMITTER_NAME,
          Git::TAG_COMMIT_HEAD_COMMITTER_EMAIL,
          Git::TAG_COMMIT_HEAD_COMMITTER_DATE,
          Git::TAG_PULL_REQUEST_BASE_BRANCH,
          Git::TAG_PULL_REQUEST_BASE_BRANCH_SHA,
          Git::TAG_PULL_REQUEST_BASE_BRANCH_HEAD_SHA
        ].freeze

        SHARED_TAGS = Set.new(SHARED_ENVIRONMENT_TAGS + Test::LibraryCapabilities::CAPABILITY_VERSIONS.keys + [
          Test::TAG_TEST_SESSION_NAME,
          Test::TAG_USER_PROVIDED_TEST_SERVICE
        ]).freeze

        PROTECTED_TAGS = Set.new([
          Test::TAG_FRAMEWORK,
          Test::TAG_FRAMEWORK_VERSION,
          Test::TAG_NAME,
          Test::TAG_SKIP_REASON,
          Test::TAG_SESSION_EMPTY_REASON,
          Test::TAG_STATUS,
          Test::TAG_FINAL_STATUS,
          Test::TAG_SUITE,
          Test::TAG_MODULE,
          Test::TAG_TYPE,
          Test::TAG_COMMAND,
          Test::TAG_SOURCE_FILE,
          Test::TAG_SOURCE_START,
          Test::TAG_SOURCE_END,
          Test::TAG_CODEOWNERS,
          Test::TAG_PARAMETERS,
          Test::TAG_CODE_COVERAGE_ENABLED,
          Test::TAG_ITR_TEST_SKIPPING_ENABLED,
          Test::TAG_ITR_TEST_SKIPPING_TYPE,
          Test::TAG_ITR_TEST_SKIPPING_COUNT,
          Test::TAG_ITR_SKIPPED_BY_ITR,
          Test::TAG_ITR_TESTS_SKIPPED,
          Test::TAG_ITR_UNSKIPPABLE,
          Test::TAG_ITR_FORCED_RUN,
          Test::TAG_TEST_SESSION_ID,
          Test::TAG_TEST_MODULE_ID,
          Test::TAG_TEST_SUITE_ID,
          Test::TAG_OS_ARCHITECTURE,
          Test::TAG_OS_PLATFORM,
          Test::TAG_OS_VERSION,
          Test::TAG_RUNTIME_NAME,
          Test::TAG_RUNTIME_VERSION,
          Test::TAG_IS_RUM_ACTIVE,
          Test::TAG_BROWSER_DRIVER,
          Test::TAG_BROWSER_DRIVER_VERSION,
          Test::TAG_BROWSER_NAME,
          Test::TAG_BROWSER_VERSION,
          Test::TAG_IS_NEW,
          Test::TAG_IS_RETRY,
          Test::TAG_RETRY_REASON,
          Test::TAG_EARLY_FLAKE_ENABLED,
          Test::TAG_EARLY_FLAKE_ABORT_REASON,
          Test::TAG_CODE_COVERAGE_LINES_PCT,
          Test::TAG_TEST_MANAGEMENT_ENABLED,
          Test::TAG_IS_ATTEMPT_TO_FIX,
          Test::TAG_IS_TEST_DISABLED,
          Test::TAG_IS_QUARANTINED,
          Test::TAG_HAS_FAILED_ALL_RETRIES,
          Test::TAG_ATTEMPT_TO_FIX_PASSED,
          Test::LibraryConfigurationError::TAG_SETTINGS,
          Test::LibraryConfigurationError::TAG_SKIPPABLE_TESTS,
          Test::LibraryConfigurationError::TAG_KNOWN_TESTS,
          Test::LibraryConfigurationError::TAG_TEST_MANAGEMENT_TESTS,
          Test::LibraryCapabilities::TAG_TEST_IMPACT_ANALYSIS,
          Test::LibraryCapabilities::TAG_EARLY_FLAKE_DETECTION,
          Test::LibraryCapabilities::TAG_AUTO_TEST_RETRIES,
          Test::LibraryCapabilities::TAG_TEST_MANAGEMENT_QUARANTINE,
          Test::LibraryCapabilities::TAG_TEST_MANAGEMENT_DISABLE,
          Test::LibraryCapabilities::TAG_TEST_MANAGEMENT_ATTEMPT_TO_FIX,
          Test::TAG_TEST_IS_MODIFIED,
          Test::TAG_SPAN_KIND,
          Test::TAG_TEST_SESSION_NAME,
          Test::TAG_USER_PROVIDED_TEST_SERVICE,
          Test::METRIC_CPU_COUNT,
          Git::TAG_BRANCH,
          Git::TAG_REPOSITORY_URL,
          Git::TAG_TAG,
          Git::TAG_COMMIT_AUTHOR_DATE,
          Git::TAG_COMMIT_AUTHOR_EMAIL,
          Git::TAG_COMMIT_AUTHOR_NAME,
          Git::TAG_COMMIT_COMMITTER_DATE,
          Git::TAG_COMMIT_COMMITTER_EMAIL,
          Git::TAG_COMMIT_COMMITTER_NAME,
          Git::TAG_COMMIT_MESSAGE,
          Git::TAG_COMMIT_SHA,
          Git::TAG_PULL_REQUEST_BASE_BRANCH,
          Git::TAG_PULL_REQUEST_BASE_BRANCH_SHA,
          Git::TAG_PULL_REQUEST_BASE_BRANCH_HEAD_SHA,
          Git::TAG_COMMIT_HEAD_SHA,
          Git::TAG_COMMIT_HEAD_MESSAGE,
          Git::TAG_COMMIT_HEAD_AUTHOR_DATE,
          Git::TAG_COMMIT_HEAD_AUTHOR_EMAIL,
          Git::TAG_COMMIT_HEAD_AUTHOR_NAME,
          Git::TAG_COMMIT_HEAD_COMMITTER_DATE,
          Git::TAG_COMMIT_HEAD_COMMITTER_EMAIL,
          Git::TAG_COMMIT_HEAD_COMMITTER_NAME,
          Environment::TAG_JOB_ID,
          Environment::TAG_JOB_NAME,
          Environment::TAG_JOB_URL,
          Environment::TAG_PIPELINE_ID,
          Environment::TAG_PIPELINE_NAME,
          Environment::TAG_PIPELINE_DISPLAY_NAME,
          Environment::TAG_PIPELINE_NUMBER,
          Environment::TAG_PIPELINE_URL,
          Environment::TAG_PROVIDER_NAME,
          Environment::TAG_STAGE_NAME,
          Environment::TAG_WORKSPACE_PATH,
          Environment::TAG_NODE_LABELS,
          Environment::TAG_NODE_NAME,
          Environment::TAG_CI_ENV_VARS,
          Environment::TAG_PR_NUMBER
        ]).freeze
      end
    end
  end
end
