# frozen_string_literal: true

module Datadog
  module CI
    module Ext
      # Constants for Test Optimization cache generated by ddtest or Bazel.
      module TestOptimizationCache
        ENV_MANIFEST_FILE = "TEST_OPTIMIZATION_MANIFEST_FILE"
        ENV_RUNFILES_DIR = "RUNFILES_DIR"
        ENV_RUNFILES_MANIFEST_FILE = "RUNFILES_MANIFEST_FILE"
        ENV_TEST_SRCDIR = "TEST_SRCDIR"

        PLAN_FOLDER = ".testoptimization"
        MANIFEST_FILE_NAME = "manifest.txt"
        SUPPORTED_MANIFEST_VERSION = "1"

        CACHE_FOLDER_NAME = "cache"
        HTTP_CACHE_FOLDER_NAME = "http"

        TESTOPTIMIZATION_CACHE_PATH = "#{PLAN_FOLDER}/#{CACHE_FOLDER_NAME}"
        TESTOPTIMIZATION_HTTP_CACHE_PATH = "#{TESTOPTIMIZATION_CACHE_PATH}/#{HTTP_CACHE_FOLDER_NAME}"

        SETTINGS_FILE_NAME = "settings.json"
        KNOWN_TESTS_FILE_NAME = "known_tests.json"
        TEST_MANAGEMENT_FILE_NAME = "test_management.json"
        LEGACY_TEST_MANAGEMENT_TESTS_FILE_NAME = "test_management_tests.json"
        SKIPPABLE_TESTS_FILE_NAME = "skippable_tests.json"
      end
    end
  end
end
