module Datadog
  module CI
    module Contrib
      module Cucumber
        module ConfigurationOverride
          def self.included: (untyped base) -> untyped
          module InstanceMethods : ::Cucumber::Configuration
            def retry_attempts: () -> Integer?

            def retry_total_tests: () -> Integer?

            def datadog_test_retries_component: () -> Datadog::CI::TestRetries::Component?
          end
        end
      end
    end
  end
end
