module Datadog
  module CI
    module Contrib
      module Cucumber
        module Ext
          ENV_ENABLED: String

          FRAMEWORK: String

          DEFAULT_SERVICE_NAME: String

          STEP_SPAN_TYPE: String
        end
      end
    end
  end
end
