module Datadog
  module CI
    module Contrib
      module Cucumber
        class Filter < ::Cucumber::Core::Filter
          interface _TestCase
            def ==: (_TestCase other) -> bool

            def describe_to: (Object receiver) -> untyped
          end

          interface _TestCaseFinishedEvent
            def test_case: () -> _TestCase
          end

          @test_case_seen: Hash[_TestCase, bool]

          @test_retries_component: Datadog::CI::TestRetries::Component

          def test_case: (_TestCase test_case) -> untyped

          private

          def retry_required?: (_TestCase test_case, _TestCaseFinishedEvent event) -> bool

          def test_case_seen: () -> Hash[_TestCase, bool]

          def test_retries_component: () -> Datadog::CI::TestRetries::Component
        end
      end
    end
  end
end
