module Datadog
  module CI
    module Contrib
      module Cucumber
        class Formatter
          private
          @failed_tests_count: Integer
          @current_test_suite: Datadog::CI::Span?
          @ast_lookup: ::Cucumber::Formatter::AstLookup

          attr_reader config: untyped

          public

          def initialize: (untyped config) -> void

          def bind_events: (untyped config) -> untyped

          def on_test_run_started: (untyped event) -> untyped

          def on_test_run_finished: (untyped event) -> untyped

          def on_test_case_started: (untyped event) -> untyped

          def on_test_case_finished: (untyped event) -> (nil | untyped)

          def on_test_step_started: (untyped event) -> untyped

          def on_test_step_finished: (untyped event) -> (nil | untyped)

          private

          def start_test_suite: (String test_suite_name) -> void

          def finish_current_test_suite: () -> void

          def same_test_suite_as_current?: (String test_suite_name) -> bool

          def finish_session: (bool result) -> void

          def finish_test: (Datadog::CI::Span test, Cucumber::Core::Test::Result result) -> void

          def extract_parameters_hash: (untyped test_case) -> Hash[String, String]?

          def configuration: () -> untyped
        end
      end
    end
  end
end
