module Datadog
  module CI
    module Contrib
      module Cucumber
        class Integration < Datadog::CI::Contrib::Integration
          MINIMUM_VERSION: Gem::Version

          def version: () -> untyped

          def loaded?: () -> bool

          def compatible?: () -> bool

          def auto_instrument?: () -> false

          def new_configuration: () -> untyped

          def patcher: () -> untyped
        end
      end
    end
  end
end
