module Datadog
  module CI
    module TestOptimisation
      module Coverage
        class Event
          @test_id: String

          @test_session_id: String

          @test_suite_id: String

          @coverage: Hash[String, untyped]

          attr_reader test_id: String

          attr_reader test_session_id: String

          attr_reader test_suite_id: String

          attr_reader coverage: Hash[String, untyped]

          def initialize: (test_id: String, test_suite_id: String, test_session_id: String, coverage: Hash[String, untyped]) -> void

          def valid?: () -> bool

          def to_msgpack: (?untyped? packer) -> untyped

          def pretty_inspect: () -> String

          def pretty_print: (untyped q) -> void

          def to_s: () -> String
        end
      end
    end
  end
end
