module Datadog
  module CI
    module Ext
      module Environment
        class LocalGit < Extractor
          private

          @commit_users: Hash[Symbol, String?]

          def git_repository_url: () -> String?

          def git_commit_sha: () -> String?

          def git_branch: () -> String?

          def git_tag: () -> String?

          def git_commit_message: () -> String?

          def git_commit_author_name: () -> String?

          def git_commit_author_email: () -> String?

          def git_commit_author_date: () -> String?

          def git_commit_committer_name: () -> String?

          def git_commit_committer_email: () -> String?

          def git_commit_committer_date: () -> String?

          def workspace_path: () -> String?

          def exec_git_command: (String cmd) -> String?

          def git_commit_users: () -> Hash[Symbol, String?]
        end
      end
    end
  end
end
