module Datadog
  module CI
    module Utils
      module Configuration
        def self.fetch_service_name: (String default) -> String

        def self.service_name_provided_by_user?: () -> bool
      end
    end
  end
end
