module Datadog
  module CI
    module Utils
      module FileStorage
        class MissingNamespaceError < StandardError
        end

        TEMP_DIR: String
        ENV_NAMESPACE: String

        def self.store: (String key, Hash[Symbol, untyped] value) -> bool

        def self.retrieve: (String key) -> Hash[Symbol, untyped]?

        def self.with_new_namespace: [T] () { (String) -> T } -> T

        def self.ensure_temp_dir_exists: () -> void

        def self.file_path_for: (String key) -> String

        def self.storage_dir: (?String namespace) -> String

        private

        def self.cleanup: (String namespace) -> bool
      end
    end
  end
end
