module Datadog
  module CI
    module Utils
      module Git
        def self.normalize_ref: (String? name) -> String?

        def self.is_git_tag?: (String? ref) -> bool
      end
    end
  end
end
