module Datadog
  module CI
    module Utils
      module Identity
        def self.included: (untyped base) -> void

        module ClassMethods
          def gem_datadog_version: () -> String
        end
      end
    end
  end
end
