module Datadog
  module CI
    module Utils
      module TestRun
        self.@command: String
        self.@virtual_cpu_count: Integer

        def self.command: () -> String

        def self.datadog_test_id: (String test_name, String? test_suite, ?String? parameters) -> String

        def self.test_parameters: (?arguments: Hash[untyped, untyped], ?metadata: Hash[untyped, untyped]) -> String

        def self.custom_configuration: (Hash[String, String]? env_tags) -> Hash[String, String]

        def self.virtual_cpu_count: () -> Integer

        def self.test_optimization_data_cached?: () -> bool
      end
    end
  end
end

module Etc
  def self.nprocessors: () -> Integer
end
