module Datadog
  module CI
    module Utils
      module TestRun
        self.@command: String

        def self.command: () -> String

        def self.test_full_name: (String test_name, String? test_suite) -> String
      end
    end
  end
end
