module Datadog
  module CI
    module Utils
      module TestRun
        self.@command: String

        def self.command: () -> String

        def self.datadog_test_id: (String test_name, String? test_suite, ?String? parameters) -> String

        def self.test_parameters: (?arguments: Hash[untyped, untyped], ?metadata: Hash[untyped, untyped]) -> String

        def self.custom_configuration: (Hash[String, String]? env_tags) -> Hash[String, String]
      end
    end
  end
end
