module Datadog
  module CI
    module ITR
      module Coverage
        class DDCov

          def initialize: (root: String, ignored_path: String?) -> void

          def start: () -> void

          def stop: () -> Hash[String, untyped]
        end
      end
    end
  end
end
