module Datadog
  module CI
    module Git
      module CLI
        class GitCommandExecutionError < StandardError
          attr_reader output: String
          attr_reader command: String
          attr_reader status: Process::Status?

          def initialize: (String message, output: String, command: String, status: Process::Status?) -> void
        end

        UNSHALLOW_TIMEOUT: Integer
        LONG_TIMEOUT: Integer
        SHORT_TIMEOUT: Integer

        self.@safe_directory: String

        def self.exec_git_command: (Array[String] cmd, ?stdin: String?, ?timeout: Integer) -> String?

        def self.safe_directory: () -> String

        def self.find_git_directory: (String start_dir) -> String
      end
    end
  end
end