module Datadog
  module CI
    module Git
      class Diff
        FILE_CHANGE_REGEX: Regexp
        LINES_CHANGE_REGEX: Regexp

        @changed_files: Hash[String, ChangedLines]

        def initialize: (?changed_files: Hash[String, ChangedLines]) -> void

        def include?: (String file_path) -> bool

        def lines_changed?: (String file_path, Integer start_line, Integer end_line) -> bool

        def changed_line_intervals: (String file_path) -> Array[Array[Integer]]

        def size: () -> Integer

        def empty?: () -> bool

        def inspect: () -> String

        def self.parse_diff_output: (String? output) -> Diff
      end
    end
  end
end