module Datadog
  module CI
    module Git
      class TreeUploader
        @api: Datadog::CI::Transport::Api::Base?
        @force_unshallow: bool

        attr_reader api: Datadog::CI::Transport::Api::Base?
        attr_reader force_unshallow: bool

        def initialize: (api: Datadog::CI::Transport::Api::Base?, ?force_unshallow: bool) -> void
        def call: (String repository_url) -> void

        private

        def fetch_known_commits_and_split: (String repository_url, Array[String] latest_commits) -> [Array[String], Array[String]]
        def test_visibility_component: () -> Datadog::CI::TestVisibility::Component
      end
    end
  end
end
