module Datadog
  module CI
    module Configuration
      module Components : Datadog::Core::Configuration::Components
        def initialize: (untyped settings) -> void

        def activate_ci!: (untyped settings) -> untyped
      end
    end
  end
end
