module Datadog
  module CI
    module Configuration
      module Components : Datadog::Core::Configuration::Components
        @ci_recorder: Datadog::CI::TestVisibility::Recorder | Datadog::CI::TestVisibility::NullRecorder
        @itr: Datadog::CI::ITR::Runner?

        attr_reader ci_recorder: Datadog::CI::TestVisibility::Recorder | Datadog::CI::TestVisibility::NullRecorder
        attr_reader itr: Datadog::CI::ITR::Runner?

        def initialize: (untyped settings) -> void

        def activate_ci!: (untyped settings) -> untyped

        def build_test_visibility_api: (untyped settings) -> Datadog::CI::Transport::Api::Base?

        def serializers_factory: (untyped settings) -> (singleton(Datadog::CI::TestVisibility::Serializers::Factories::TestSuiteLevel) | singleton(Datadog::CI::TestVisibility::Serializers::Factories::TestLevel))

        def check_dd_site: (untyped settings) -> void

        def timecop?: () -> bool
      end
    end
  end
end
