module Datadog
  module CI
    module Ext
      module Environment
        module Providers
          class GithubActions < Base
            GITHUB_RUNNER_DIAG_PATHS: Array[String]
            CHECK_RUN_ID_REGEX: Regexp

            @ref: String
            @github_server_url: String?
            @github_event_json: Hash[String, untyped]?
            @numeric_job_id: String?

            def self.handles?: (Hash[String, String] env) -> bool

            def provider_name: () -> String

            def job_name: () -> String?

            def job_url: () -> String

            def job_id: () -> String?

            def pipeline_id: () -> String?

            def pipeline_name: () -> String?

            def pipeline_number: () -> String?

            def pipeline_url: () -> String

            def workspace_path: () -> String?

            def git_repository_url: () -> String

            def git_commit_sha: () -> String?

            def git_branch_or_tag: () -> String?

            def ci_env_vars: () -> String

            def git_pull_request_base_branch: () -> String?

            def git_pull_request_base_branch_head_sha: () -> String?

            def git_commit_head_sha: () -> String?

            def pr_number: () -> Integer?

            private

            def github_event_json: () -> Hash[String, untyped]?

            def github_server_url: () -> String?

            def numeric_job_id: () -> String?

            def extract_numeric_job_id_from_diag_files: () -> String?

            def extract_check_run_id_from_worker_file: (String file_path) -> String?
          end
        end
      end
    end
  end
end
