module Datadog
  module CI
    module TestTracing
      module DeprecatedTotalCoverageMetric
        def self.extract_lines_pct: (Datadog::CI::TestSession test_session) -> void

        def self.simplecov_running?: () -> bool
      end
    end
  end
end
