module Datadog
  module CI
    module TestTracing
      module DeprecatedTotalCoverageMetric
        def self.extract_lines_pct: (Datadog::CI::TestSession test_session) -> void
      end
    end
  end
end
