module Datadog
  module CI
    module TestTracing
      class NullComponent
        @known_tests: Set[String]
        @known_tests_enabled: bool
        @context_service_uri: nil
        @local_test_suites_mode: bool

        attr_reader known_tests: Set[String]
        attr_reader known_tests_enabled: bool
        attr_reader context_service_uri: nil
        attr_reader local_test_suites_mode: bool

        def initialize: () -> void

        def configure: (untyped _, untyped _) -> void

        def trace_test: (String span_name, String test_suite_name, ?service: String?, ?tags: Hash[untyped, untyped]) ?{ (nil span) -> untyped } -> untyped

        def trace: (String span_name, ?type: String, ?tags: Hash[untyped, untyped]) ?{ (Datadog::CI::Span span) -> untyped } -> untyped

        def start_test_session: (
          ?service: String?, ?tags: Hash[untyped, untyped], ?estimated_total_tests_count: Integer, ?distributed: bool?, ?local_test_suites_mode: bool
        ) -> nil

        def start_test_module: (String test_module_name, ?service: String?, ?tags: Hash[untyped, untyped]) -> nil

        def start_test_suite: (String test_suite_name, ?service: String?, ?tags: Hash[untyped, untyped]) -> nil

        def active_test_session: () -> nil

        def active_test_module: () -> nil

        def active_test_suite: (String? test_suite_name) -> nil

        def active_test: () -> nil

        def active_span: () -> nil

        def deactivate_test: () -> void

        def deactivate_test_session: () -> void

        def deactivate_test_module: () -> void

        def deactivate_test_suite: (String test_suite_name) -> void

        def logical_test_session_name: () -> nil

        def shutdown!: () -> nil

        def itr_enabled?: () -> bool

        def client_process?: () -> bool

        def restore_state_from_datadog_test_runner: () -> bool

        private

        def skip_tracing: (?untyped block) -> nil
      end
    end
  end
end
