module Datadog
  module CI
    module TestTracing
      module Telemetry
        SPAN_TYPE_TO_TELEMETRY_EVENT_TYPE: ::Hash[String, String]
        def self.event_created: (Datadog::CI::Span span) -> void

        def self.event_finished: (Datadog::CI::Span span) -> void

        def self.test_session_started: (Datadog::CI::TestSession span) -> void

        def self.event_tags_from_span: (Datadog::CI::Span span) -> ::Hash[String, String]

        def self.add_browser_tags!: (Datadog::CI::Span span, ::Hash[String, String] tags) -> void

        def self.agentless_logs_component: () -> Datadog::CI::Logs::Component?
      end
    end
  end
end
