module Datadog
  module CI
    module Transport
      module Api
        class Agentless < Base
          attr_reader api_key: String

          @api_key: String

          def initialize: (api_key: String, http: Datadog::CI::Transport::HTTP) -> void

          def request: (path: String, payload: String, ?headers: Hash[String, String], ?verb: ::String) -> Datadog::CI::Transport::HTTP::ResponseDecorator

          private

          def default_headers: () -> Hash[String, String]
        end
      end
    end
  end
end
