module Datadog
  module CI
    module Transport
      module Api
        class Base
          @citestcov_payload: String

          def api_request: (path: String, payload: String, ?headers: Hash[String, String], ?verb: ::String) -> untyped

          def citestcycle_request: (path: String, payload: String, ?headers: Hash[String, String], ?verb: ::String) -> untyped

          def citestcov_request: (path: String, payload: String, ?headers: Hash[String, String], ?verb: ::String) -> untyped

          private

          def headers_with_default: (Hash[String, String] headers) -> Hash[String, String]

          def default_headers: () -> Hash[String, String]
        end
      end
    end
  end
end
