module Datadog
  module CI
    module Transport
      module Api
        module Builder
          interface _CISettings
            def agentless_url: () -> String?
          end

          interface _SettingsExtras
            def api_key: () -> String

            def site: () -> String?

            def ci: () -> _CISettings
          end

          def self.build_agentless_api: ((::Datadog::Core::Configuration::Settings & _SettingsExtras) settings) -> Datadog::CI::Transport::Api::Agentless?
          def self.build_evp_proxy_api: ((::Datadog::Core::Configuration::Settings & _SettingsExtras) settings) -> Datadog::CI::Transport::Api::EvpProxy?
        end
      end
    end
  end
end
