module Datadog
  module CI
    module TestOptimizationCache
      module Readers
        class Legacy < Base
          def load_settings: () -> Hash[String, untyped]?

          def load_known_tests: () -> Hash[String, untyped]?

          def load_test_management: () -> Hash[String, untyped]?

          def load_skippable_tests: () -> Hash[String, untyped]?

          private

          def load_legacy_json: (String file_name) -> Hash[String, untyped]?

          def backend_response: (Hash[String, untyped] payload) -> Hash[String, untyped]

          def skippable_tests_response: (Hash[String, untyped] payload) -> Hash[String, untyped]
        end
      end
    end
  end
end
