module Datadog
  module CI
    module TestOptimizationCache
      module Readers
        class Missing < Base
          def available?: () -> false

          def load_settings: () -> nil

          def load_known_tests: () -> nil

          def load_test_management: () -> nil

          def load_skippable_tests: () -> nil
        end
      end
    end
  end
end
