module Datadog
  module CI
    module TestVisibility
      class KnownTests
        @api: Datadog::CI::Transport::Api::Base?
        @dd_env: String?
        @config_tags: Hash[String, String]

        class Response
          @http_response: Datadog::CI::Transport::Adapters::Net::Response?
          @json: Hash[String, untyped]?

          def self.from_http_response: (Datadog::CI::Transport::Adapters::Net::Response http_response) -> Response

          def self.from_json: (Hash[String, untyped] json) -> Response

          def ok?: () -> bool

          def tests: () -> Set[String]

          def cursor: () -> String?

          def has_next?: () -> bool

          private

          def initialize: (Datadog::CI::Transport::Adapters::Net::Response? http_response, Hash[String, untyped]? json) -> void

          def payload: () -> Hash[String, untyped]

          def page_info: () -> Hash[String, untyped]
        end

        def initialize: (?api: Datadog::CI::Transport::Api::Base?, dd_env: String?, ?config_tags: Hash[String, String]) -> void

        def fetch: (Datadog::CI::TestSession test_session) -> Set[String]

        private

        def fetch_page: (Datadog::CI::Transport::Api::Base api, Datadog::CI::TestSession test_session, ?page_state: String?) -> Response

        def payload: (Datadog::CI::TestSession test_session, ?page_state: String?) -> String
      end
    end
  end
end
