# frozen_string_literal: true

class RubyVM::InstructionSequence
  def to_a: () -> Array[untyped]
end

module Datadog
  module CI
    module SourceCode
      ISEQ_HASH_LENGTH: 16
      ISEQ_HASH_NATIVE_AVAILABLE: bool
      ISEQ_SIMPLE_DATA_FORMAT: "YARVInstructionSequence/SimpleDataFormat"
      ISEQ_METADATA_KEYS: Array[Symbol]

      type iseq_hash_target = Proc | Method | UnboundMethod | RubyVM::InstructionSequence

      def self.iseq_hash: (iseq_hash_target? target) -> String
      def self._native_iseq_hash: (iseq_hash_target? target) -> String?
      def self._native_iseq_hash_from_iseq: (RubyVM::InstructionSequence iseq) -> String

      private

      def self.iseq_for: (iseq_hash_target? target) -> RubyVM::InstructionSequence?
      def self.normalize_iseq_array: (Array[untyped] iseq_array) -> untyped
      def self.iseq_array?: (untyped value) -> bool
      def self.normalize_iseq_metadata: (Hash[untyped, untyped] metadata) -> Hash[Symbol, untyped]
      def self.normalize_body: (untyped body) -> untyped
      def self.normalize_value: (untyped value) -> untyped
      def self.warn_iseq_hash_error: (StandardError error) -> void
      def self.warn_iseq_hash_message: (String message) -> void
      def self.warn_iseq_hash_message_fallback: (String message) -> void
    end
  end
end
