# frozen_string_literal: true

class RubyVM::InstructionSequence
  def self.of: (Proc | Method target) -> RubyVM::InstructionSequence?
end

module Datadog
  module CI
    module SourceCode
      module MethodInspect
        LAST_LINE_AVAILABLE: bool

        def self.last_line: (Proc? | Method? target) -> Integer?

        def self._native_last_line_from_iseq: (RubyVM::InstructionSequence iseq) -> Integer?
      end
    end
  end
end
