name: Add milestone to pull requests
on:
  pull_request:
    types: [closed]

jobs:
  add_milestone:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    runs-on: ubuntu-24.04
    if: github.event.pull_request.merged == true && github.event.pull_request.milestone == null
    steps:
      - name: Checkout code
        # Checks out the branch that the pull request is merged into
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Get major version from gemspec
        # Parse the gemspec and return the major version
        id: version
        run: |
          echo "::set-output name=version::$(find . -name *.gemspec | ruby -ne 'puts Gem::Specification.load($_.chomp).version.to_s.split(".").first')"

      - name: Get project milestones
        id: milestones
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const milestones = await github.rest.issues.listMilestones({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            })
            return milestones.data

      - name: Update Pull Request
        # Update the merged pull request with the milestone starts with the major version
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const milestones = ${{steps.milestones.outputs.result}}
            const majorVersion = ${{steps.version.outputs.version}}
            const milestone = milestones.find(m => m.title.startsWith(majorVersion))

            if (milestone) {
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: ${{ github.event.pull_request.number }},
                milestone: milestone.number
              })
            }
