name: 'Integration test run'
on:
  # Build each branch for testing
  push:
  # Also test pull requests opened from forks.
  pull_request:

jobs:
  build_and_run_integration_test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        ruby_image:
          - ruby:3.0
          - ruby:3.1
          - ruby:3.2
          - ruby:3.3
    steps:
      - name: Checkout datadog-ci
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1
      - name: Run test
        working-directory: integration/app
        run: |
          BASE_IMAGE=${{matrix.ruby_image}} docker compose run --rm --no-deps app "bundle install && bundle exec rake test"
