name: "Integration test run"
on:
  # Build each branch for testing
  push:

jobs:
  build_and_run_integration_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout datadog-ci
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Run test
        working-directory: integration/app
        run: |
          docker compose run --rm --no-deps app "bundle install && bundle exec rake test"
