name: Test for memory leaks
on: [push]
jobs:
  test-memcheck:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ruby/setup-ruby@14594264cd68ce8a2345dd349bc3d138a4ef85c8 # v1.327.0
        with:
          ruby-version: '3.4.5'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          bundler: latest
          cache-version: v2 # bump this to invalidate cache
      - run: sudo apt-get update && (sudo apt-get install -y valgrind || sleep 5 && sudo apt-get install -y valgrind) && valgrind --version
      - run: bundle exec rake compile spec:ddcov_memcheck
