module Datadog
  module CI
    module Transport
      class ApiClient
        @api: untyped

        def initialize: (?api: Datadog::CI::Transport::Api::Base?) -> void

        def fetch_library_settings: (service: String?) -> untyped

        private

        def settings_payload: (service: String?) -> String
      end
    end
  end
end
