module Datadog
  module CI
    module Transport
      class HTTP
        @adapter: Datadog::CI::Transport::Adapters::Net

        attr_reader host: String
        attr_reader port: Integer
        attr_reader ssl: bool
        attr_reader timeout: Integer
        attr_reader compress: bool

        DEFAULT_TIMEOUT: 30
        MAX_RETRIES: 3
        INITIAL_BACKOFF: 1

        def initialize: (host: String, port: Integer, ?ssl: bool, ?timeout: Integer, ?compress: bool) -> void

        def request: (?verb: String, payload: String, headers: Hash[String, String], path: String, ?retries: Integer, ?backoff: Integer, ?accept_compressed_response: bool) -> Datadog::CI::Transport::Adapters::Net::Response

        private

        def adapter: () -> Datadog::CI::Transport::Adapters::Net

        def perform_http_call: (payload: String, headers: Hash[String, String], path: String, verb: String, ?retries: Integer, ?backoff: Integer) -> Datadog::CI::Transport::Adapters::Net::Response

        class ErrorResponse < Datadog::CI::Transport::Adapters::Net::Response
          def initialize: (StandardError error) -> void
        end
      end
    end
  end
end

