module Datadog
  module CI
    module Transport
      module Telemetry
        def self.events_enqueued_for_serialization: (Integer count) -> void

        def self.endpoint_payload_events_count: (Integer count, String endpoint) -> void
      end
    end
  end
end
