module Datadog
  module CI
    module TestImpactAnalysis
      module SkippablePercentage
        class Estimator < Base
          def initialize: (?verbose: bool, ?spec_path: ::String) -> void

          def call: () -> Numeric
        end
      end
    end
  end
end
