module Datadog
  module CI
    module Contrib
      module Knapsack
        class Integration < Datadog::CI::Contrib::Integration
          MINIMUM_VERSION: Gem::Version

          def version: () -> untyped

          def loaded?: () -> bool

          def compatible?: () -> bool

          def auto_instrument?: () -> bool

          def new_configuration: () -> Datadog::CI::Contrib::Settings

          def patcher: () -> singleton(Patcher)
        end
      end
    end
  end
end
